# Generated by Django 3.2 on 2021-04-11 18:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Asset.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text="Enter the Asset's Name", max_length=50)),
                ('asset_tag', models.CharField(default='', help_text="Enter the Asset's Asset Tag.", max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('purchase_date', models.DateField(default=datetime.date.today, help_text='Enter the date the Asset was purchased.')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(default='', help_text='Enter notes for the Asset.', max_length=2000)),
                ('physical', models.BooleanField(default=False, help_text='Is the Asset physical?', null=True)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
