# Generated by Django 3.2 on 2021-04-11 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status_labels', '0001_initial'),
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='assigned_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hardware',
            name='categorization',
            field=models.CharField(default='', help_text="Enter the Asset's Security Categorization", max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='location_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.location'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='status_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='status_labels.status_label'),
        ),
    ]
