# Generated by Django 3.2 on 2021-04-11 18:55

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Location.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text="Enter the Location's Name", max_length=500)),
                ('city', models.CharField(blank=True, default='', help_text='Enter the city in which the Location is located', max_length=500)),
                ('state', models.CharField(blank=True, default='', help_text='Enter the state in which the Location is located', max_length=500, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Invalid State Format')])),
                ('zip', models.CharField(blank=True, default='', help_text='Enter the zip code of the Location', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$', 'Invalid Zip Code Format')])),
                ('country', models.CharField(blank=True, default='', help_text='Enter the country in which the Location is located', max_length=500)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
