# Generated by Django 3.2 on 2021-04-11 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Manufacturer.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text="Enter the Manufacturer's Name", max_length=50)),
                ('modelno', models.IntegerField(default=1)),
                ('url', models.CharField(default='', help_text="Enter the Manufacturer's Web Site URL", max_length=200)),
                ('manufacturer_id', models.ManyToManyField(blank=True, related_name='manufacturer', to='manufacturers.Manufacturer')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
